# Generated by Django 6.1 on 2026-09-02 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(default='system', max_length=8)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('strategy_key', models.CharField(blank=True, max_length=40)),
                ('text', models.CharField(max_length=400)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SignupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('make_operator', models.BooleanField(default=False, help_text='Can start/stop the agent and change settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['market', 'mode']},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['market', 'name'], 'verbose_name_plural': 'strategies'},
        ),
        migrations.AddField(
            model_name='account',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto')], default='stocks', max_length=8),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto')], default='stocks', max_length=8),
        ),
        migrations.AddField(
            model_name='strategy',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='mode',
            field=models.CharField(choices=[('sim', 'Sim'), ('paper', 'Paper'), ('live', 'Live'), ('replay', 'Replay')], max_length=8),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='key',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('mode', 'market'), name='uniq_account_mode_market'),
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('key', 'market'), name='uniq_strategy_key_market'),
        ),
        migrations.AddField(
            model_name='feedevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='main_app.account'),
        ),
        migrations.AddField(
            model_name='signupinvite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['account', 'id'], name='main_app_fe_account_6c5a10_idx'),
        ),
    ]
