# Generated by Django 6.1 on 2026-09-02 05:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feedevent_signupinvite_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='crypto_timeframe',
            field=models.CharField(default='1Hour', max_length=8),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='min_reward_to_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=5),
        ),
    ]
