# Generated by Django 6.1 on 2026-09-02 05:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_agentconfig_crypto_timeframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='day_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='day_halted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='day_halted_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='last_reconcile_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reconcile_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='account',
            name='reconcile_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='live_confirm_minutes',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='data_source',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='expected_interval_s',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='last_bar_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='state',
            field=models.CharField(default='starting', max_length=12),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedevent',
            name='bar_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedevent',
            name='phase',
            field=models.CharField(default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='position',
            name='closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='protection',
            field=models.CharField(default='engine', max_length=12),
        ),
        migrations.AddField(
            model_name='position',
            name='protection_order_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedevent',
            name='text',
            field=models.CharField(max_length=600),
        ),
        migrations.CreateModel(
            name='TradeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_order_id', models.CharField(max_length=120, unique=True)),
                ('symbol', models.CharField(max_length=16)),
                ('strategy_key', models.CharField(blank=True, max_length=40)),
                ('side', models.CharField(default='long', max_length=5)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('bar_ts', models.DateTimeField(blank=True, null=True)),
                ('decision_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('planned_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('qty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('risk_dollars', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reward_dollars', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('expected_costs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reward_risk', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('broker_order_id', models.CharField(blank=True, max_length=80)),
                ('protection', models.CharField(default='none', max_length=12)),
                ('protection_order_id', models.CharField(blank=True, max_length=80)),
                ('filled_qty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('avg_fill', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fees', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('slippage_bps', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=16)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gross_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('approval_expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=80)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main_app.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedevent',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='main_app.tradecard'),
        ),
        migrations.CreateModel(
            name='SymbolState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('bar_ts', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('source', models.CharField(blank=True, max_length=24)),
                ('decision', models.CharField(default='wait', max_length=12)),
                ('summary', models.CharField(blank=True, max_length=600)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('proximity', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_states', to='main_app.account')),
            ],
            options={
                'ordering': ['-proximity', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('account', 'symbol'), name='uniq_symbol_state')],
            },
        ),
        migrations.AddIndex(
            model_name='tradecard',
            index=models.Index(fields=['account', 'status'], name='main_app_tr_account_6c8674_idx'),
        ),
    ]
