# Generated by Django 6.1 on 2026-09-02 07:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_account_day_entries_account_day_halted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='degen_max_daily_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_max_hold_minutes',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_max_open_positions',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_max_position_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_max_trades_per_day',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_min_reward_to_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.2'), max_digits=5),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_risk_per_trade_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('3'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='degen_timeframe',
            field=models.CharField(default='1Min', max_length=8),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='pulse_seconds',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='instrument',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='fill',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tick_size',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='decision_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='filled_avg_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradecard',
            name='avg_fill',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradecard',
            name='decision_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradecard',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradecard',
            name='planned_entry',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradecard',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradecard',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
