# Generated by Django 6.1 on 2026-09-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_degen_lane_and_prices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bar',
            name='uniq_bar',
        ),
        migrations.RemoveIndex(
            model_name='bar',
            name='main_app_ba_instrum_cd4b93_idx',
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['instrument', 'timeframe', 'source', 'ts'], name='main_app_ba_instrum_91d957_idx'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(fields=('instrument', 'timeframe', 'source', 'ts'), name='uniq_bar'),
        ),
    ]
