# Generated by Django 6.1 on 2026-09-07 06:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_bar_per_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='fee_bps_forex',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_leverage',
            field=models.DecimalField(decimal_places=1, default=Decimal('10'), max_digits=5),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_max_daily_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_max_hold_minutes',
            field=models.PositiveIntegerField(default=240),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_max_open_positions',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_max_position_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=7),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_max_trades_per_day',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_min_reward_to_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_risk_per_trade_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_slippage_bps',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.3'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='forex_timeframe',
            field=models.CharField(default='5Min', max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('crypto', 'Crypto'), ('forex', 'Forex')], default='stock', max_length=8),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], default='stocks', max_length=8),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], default='stocks', max_length=8),
        ),
    ]
