# Generated by Django 6.1 on 2026-09-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_forex_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='forex_timeframe',
            field=models.CharField(default='15Min', max_length=8),
        ),
    ]
