# Generated by Django 6.1 on 2026-09-09 08:49

from decimal import Decimal
from decimal import Decimal

from django.db import migrations, models


def move_lanes_to_viable_timeframes(apps, schema_editor):
    """Apply the new defaults to the LIVE config row, not just to fresh installs.

    Measured 2026-09-09 over 200 days of Alpaca bars, typical 2-ATR target as a
    multiple of the 0.56% crypto round trip:
        crypto  1Hour 2.1-2.6x    4Hour 4.3-5.5x
        degen   1Min  0.3-0.7x    15Min 1.4-2.3x
    A degen trade on 1-minute bars was paying a fee larger than the move it was
    trying to capture, which is why that lane lost $2,210 with $1,698 of fees.
    """
    AgentConfig = apps.get_model('main_app', 'AgentConfig')
    Strategy = apps.get_model('main_app', 'Strategy')
    for cfg in AgentConfig.objects.all():
        cfg.crypto_timeframe = '4Hour'
        cfg.degen_timeframe = '15Min'
        cfg.degen_min_reward_to_cost = Decimal('1.5')
        cfg.degen_max_hold_minutes = 180
        cfg.degen_max_directional_exposure_pct = Decimal('50')
        cfg.save(update_fields=['crypto_timeframe', 'degen_timeframe', 'degen_min_reward_to_cost',
                                'degen_max_hold_minutes', 'degen_max_directional_exposure_pct'])
    Strategy.objects.filter(market='crypto').update(timeframe='4Hour')
    Strategy.objects.filter(market='degen').update(timeframe='15Min')


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_forex_directional_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='degen_max_directional_exposure_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='crypto_timeframe',
            field=models.CharField(default='4Hour', max_length=8),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_max_hold_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_min_reward_to_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_timeframe',
            field=models.CharField(default='15Min', max_length=8),
        ),
        migrations.RunPython(move_lanes_to_viable_timeframes, migrations.RunPython.noop),
    ]
