# Generated by Django 6.1 on 2026-09-09 09:04

from django.db import migrations, models
from django.utils import timezone


def reset_evidence_for_retimeframed_lanes(apps, schema_editor):
    """Crypto moved to 4Hour and degen to 15Min in 0011, so their forward
    evidence starts now. Degen's burst was quarantined on 165 trades taken at
    1Min, where the fee exceeded the typical move — a verdict about a
    configuration that no longer exists. Lift it and re-observe."""
    Strategy = apps.get_model('main_app', 'Strategy')
    now = timezone.now()
    for row in Strategy.objects.filter(market__in=('crypto', 'degen')):
        row.evidence_since = now
        if row.qualification == 'quarantine':
            row.qualification = 'unproven'
            row.qualification_reason = ('quarantine lifted: it was earned on 1-minute bars where the 0.56% round '
                                        'trip exceeded the typical move, and the lane now runs a timeframe where a '
                                        'target can clear costs. Re-observing from scratch.')[:300]
            row.qualification_updated_at = now
        row.save(update_fields=['evidence_since', 'qualification', 'qualification_reason', 'qualification_updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_lane_costs_and_correlation'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='evidence_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
            migrations.RunPython(reset_evidence_for_retimeframed_lanes, migrations.RunPython.noop),
    ]
