# Generated by Django 6.1 on 2026-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_evidence_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='cached_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='calls',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='project',
            field=models.CharField(default='moneytree', max_length=30),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='provider',
            field=models.CharField(default='anthropic', max_length=20),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['ts', 'project'], name='main_app_ap_ts_2c2095_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['provider', 'model'], name='main_app_ap_provide_2434ef_idx'),
        ),
    ]
