# Generated by Django 6.1 on 2026-09-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_spend_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='alpaca', max_length=40)),
                ('published_at', models.DateTimeField()),
                ('headline', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('symbols', models.JSONField(blank=True, default=list)),
                ('market', models.CharField(blank=True, choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], max_length=8)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=16)),
                ('direction', models.CharField(blank=True, max_length=8)),
                ('magnitude', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('horizon', models.CharField(blank=True, max_length=12)),
                ('novel', models.BooleanField(default=True)),
                ('rationale', models.CharField(blank=True, max_length=400)),
                ('tradable', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('price_at_news', models.JSONField(blank=True, default=dict)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='main_app.newsitem')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='main_app_ne_publish_9aa980_idx'), models.Index(fields=['market', '-published_at'], name='main_app_ne_market_8f3c2c_idx'), models.Index(fields=['kind', 'direction'], name='main_app_ne_kind_5f4265_idx')],
            },
        ),
    ]
