# Generated by Django 6.1 on 2026-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='news_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
