# Generated by Django 6.1 on 2026-09-12 14:56

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_news_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], max_length=8)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('quiet', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('cost_usd', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['market', '-ts'], name='main_app_br_market_d90878_idx')],
            },
        ),
    ]
