# Generated by Django 6.1 on 2026-09-14 00:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_briefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_max_daily_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_max_position_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_max_trades_per_day',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_min_reward_to_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='degen_risk_per_trade_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6),
        ),
    ]
