# Generated by Django 6.1 on 2026-09-15 23:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_degen_risk_parity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('narrative', models.TextField(blank=True)),
                ('considered', models.PositiveIntegerField(default=0)),
                ('actionable', models.PositiveIntegerField(default=0)),
                ('traded', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('duration_s', models.FloatField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('symbol', models.CharField(blank=True, max_length=16)),
                ('market', models.CharField(blank=True, choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], max_length=8)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('short', 'Short'), ('none', 'No action')], default='none', max_length=6)),
                ('thesis', models.TextField(blank=True)),
                ('horizon', models.CharField(blank=True, max_length=12)),
                ('tradable', models.BooleanField(default=False)),
                ('acted', models.BooleanField(default=False)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('price_at_verdict', models.FloatField(blank=True, null=True)),
                ('outcome_pct', models.FloatField(blank=True, null=True)),
                ('outcome_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdicts', to='main_app.newsitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='main_app.newssession')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_verdicts', to='main_app.trade')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['session', '-score'], name='main_app_ne_session_abe2d6_idx'), models.Index(fields=['symbol', '-created_at'], name='main_app_ne_symbol_5d8658_idx')],
            },
        ),
    ]
