# Generated by Django 6.1 on 2026-09-16 19:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_news_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='news_daily_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='news_max_consecutive_losses',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='news_max_correlated_exposure_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=7),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='news_max_same_direction_positions',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='news_slippage_trip_multiple',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='news_weekly_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=6),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='research_budget_usd_per_day',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=8),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='estimated_usd',
            field=models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='provisional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='reasoning_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='reservation_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='search_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='search_content_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='service_tier',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='state',
            field=models.CharField(choices=[('settled', 'Settled'), ('reserved', 'Reserved'), ('failed', 'Failed')], default='settled', max_length=8),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='arm',
            field=models.CharField(default='headline', max_length=16),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='atr_at_verdict',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='event_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='horizon_bucket',
            field=models.CharField(default='B0', max_length=2),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='lease_owner',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='lease_state',
            field=models.CharField(choices=[('available', 'Available'), ('leased', 'Leased'), ('consumed', 'Consumed')], default='available', max_length=10),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='mae_atr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='mfe_atr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='outcome_atr_net',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='outcome_kind',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='provenance',
            field=models.CharField(choices=[('contemporaneous', 'Recorded before the fact'), ('reconstructed', 'Rebuilt afterwards')], default='contemporaneous', max_length=16),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['state', '-ts'], name='main_app_ap_state_b5f3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='newsverdict',
            index=models.Index(fields=['event_key', 'lease_state'], name='main_app_ne_event_k_654ee8_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiusage',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_key', ''), _negated=True), fields=('reservation_key',), name='uniq_api_reservation_key'),
        ),
        migrations.AddConstraint(
            model_name='newsverdict',
            constraint=models.UniqueConstraint(condition=models.Q(('lease_state', 'leased'), models.Q(('event_key', ''), _negated=True)), fields=('event_key',), name='uniq_leased_event'),
        ),
    ]
