# Generated by Django 6.1 on 2026-09-16 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_mark_history_reconstructed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='article_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='first_public_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='ingested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='decision_eligible_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='quote_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='research_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='research_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['article_id'], name='main_app_ne_article_6467a1_idx'),
        ),
    ]
