# Generated by Django 6.1 on 2026-09-16 21:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_backfill_news_clocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('market', models.CharField(blank=True, choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], max_length=8)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('arm', models.CharField(choices=[('shadow', 'Shadow'), ('armed', 'Armed')], default='shadow', max_length=8)),
                ('research_started_at', models.DateTimeField(blank=True, null=True)),
                ('research_completed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('stories', models.JSONField(blank=True, default=list)),
                ('bull', models.JSONField(blank=True, default=list)),
                ('bear', models.JSONField(blank=True, default=list)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True)),
                ('catalyst_headline', models.CharField(blank=True, max_length=500)),
                ('catalyst_url', models.URLField(blank=True, max_length=500)),
                ('catalyst_at', models.DateTimeField(blank=True, null=True)),
                ('score_catalyst', models.PositiveSmallIntegerField(default=0)),
                ('score_context', models.PositiveSmallIntegerField(default=0)),
                ('score_thesis', models.PositiveSmallIntegerField(default=0)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('short', 'Short'), ('none', 'No action')], default='none', max_length=6)),
                ('p_target_first', models.FloatField(blank=True, null=True)),
                ('p_stop_first', models.FloatField(blank=True, null=True)),
                ('p_timeout', models.FloatField(blank=True, null=True)),
                ('p_positive_net', models.FloatField(blank=True, null=True)),
                ('p_low', models.FloatField(blank=True, null=True)),
                ('p_high', models.FloatField(blank=True, null=True)),
                ('base_rate', models.FloatField(blank=True, null=True)),
                ('size_multiplier', models.FloatField(default=1.0)),
                ('veto_reason', models.CharField(blank=True, max_length=300)),
                ('refused_reason', models.CharField(blank=True, max_length=300)),
                ('thin_evidence', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('service_tier', models.CharField(blank=True, max_length=12)),
                ('searches', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=5, default=Decimal('0'), max_digits=10)),
                ('duration_s', models.FloatField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['symbol', '-as_of'], name='main_app_sy_symbol_b50cbd_idx'), models.Index(fields=['-as_of'], name='main_app_sy_as_of_10e7ac_idx')],
            },
        ),
        migrations.AddField(
            model_name='newsverdict',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdicts', to='main_app.symboldossier'),
        ),
    ]
