# Generated by Django 6.1 on 2026-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_phase3_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='lifetime_halt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='lifetime_halt_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
