# Generated by Django 6.1 on 2026-09-17 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_lifetime_brake'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentions', models.PositiveIntegerField(default=1)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-mentions', '-last_seen'],
                'indexes': [models.Index(fields=['-last_seen'], name='main_app_un_last_se_024150_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol',), name='uniq_unmatched_symbol')],
            },
        ),
    ]
