# Generated by Django 6.1 on 2026-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_unmatched_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='epoch_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='epoch_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
