# Generated by Django 6.1 on 2026-09-23 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_account_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='review_halt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='review_halt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='review_halt_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ReviewRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('operational', 'Operational'), ('improvement', 'Improvement')], max_length=12)),
                ('trigger', models.CharField(default='schedule', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=10)),
                ('checks_run', models.PositiveIntegerField(default=0)),
                ('checks_failed', models.PositiveIntegerField(default=0)),
                ('findings_opened', models.PositiveIntegerField(default=0)),
                ('findings_repeated', models.PositiveIntegerField(default=0)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cycle', '-started_at'], name='main_app_re_cycle_b6f5bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('market', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('degen', 'Degen'), ('forex', 'Forex')], default='forex', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('claim', models.TextField()),
                ('source', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('backtested', 'Backtested'), ('rejected', 'Rejected'), ('forward_testing', 'Forward testing'), ('accepted', 'Accepted')], default='proposed', max_length=16)),
                ('train_result', models.JSONField(blank=True, default=dict)),
                ('test_result', models.JSONField(blank=True, default=dict)),
                ('paper_result', models.JSONField(blank=True, default=dict)),
                ('challenge', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.CharField(blank=True, max_length=80)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses', to='main_app.reviewrun')),
            ],
            options={
                'verbose_name_plural': 'hypotheses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(default='operational', max_length=12)),
                ('check_key', models.CharField(max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warn', 'Warning'), ('info', 'Info')], default='warn', max_length=8)),
                ('fingerprint', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.CharField(blank=True, max_length=60)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=14)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_findings', to='main_app.account')),
                ('first_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_findings', to='main_app.reviewrun')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_findings', to='main_app.reviewrun')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='main_app_re_status_a43f8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'check_key', 'fingerprint'), name='uniq_finding_fingerprint')],
            },
        ),
    ]
