# Generated by Django 6.1 on 2026-09-23 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_review_cycles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('conversion', 'Currency conversion'), ('fee', 'Fee'), ('interest', 'Interest or financing'), ('adjustment', 'Broker adjustment'), ('dividend', 'Dividend')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('from_currency', models.CharField(blank=True, max_length=8)),
                ('from_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('broker_ref', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='local', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='main_app.account')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['account', '-ts'], name='main_app_ca_account_1f83f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('broker_ref__gt', '')), fields=('account', 'broker_ref'), name='uniq_cash_movement_broker_ref')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=True)),
                ('our_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('broker_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('our_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('broker_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('our_fees', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('broker_fees', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('positions_checked', models.PositiveIntegerField(default=0)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='main_app.account')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['account', '-ts'], name='main_app_re_account_482cb6_idx')],
            },
        ),
    ]
