# Generated by Django 6.1 on 2026-10-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_strategy_timeframe_follows_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='strategy_max_hold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_hold_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
